### ISSUE TITLE
고칠점 스프린트

### ISSUE THREAD

**Issue by janghoosa** [Palgona/Backend#117]
## Description

- 아래 TODO에 고칠 점을 적어주세요.

## Todo

- [ ] 로깅 - 파일로 남기기
- [x] 서브모듈 설정
- [ ] init SQL 설정
- [ ] 알림 기능
- [ ] 경매 기능 리팩토링
  - [ ] findHighestPriceBy 메서드 직접 쿼리 작성
- [ ] 상품 조회 기능 리팩토링
- [ ] 성능 테스트
- [ ] 성능 visualization 추가
