### ISSUE TITLE
상품 조회 API

### ISSUE THREAD

**Issue by jinsu868** [Palgona/Backend#28]
## Description

- 상품 리스트 조회 API

## Todo

- [x] 최신순 조회 API
- [x] 마감순 조회 API
- [x] 참여자순 조회 API
- [x] 카테고리별 최고가, 최저가 조회 API
