### ISSUE TITLE
상품 관련 API 수정

### ISSUE THREAD

**Issue by JangWooJin1** [Palgona/Backend#45]
## Description

- 상품 관련 API에 대한 추가적인 작업

## Todo
- [x] 상품 상세 조회 API 수정
  - 삭제된 상품 조회 처리
  - 현재 입찰 최고가, 찜 정보 가져오기
- [x] 상품 삭제 API 수정
  - 상품과 관련된 찜 정보들 삭제
- [x] 상품 등록 및 수정 API 수정
  - 상품 정보 유효성 확인( 가격, 카테고리, 판매 기간 )
