### ISSUE TITLE
상품 관련 API 테스트

### ISSUE THREAD

**Issue by JangWooJin1** [Palgona/Backend#47]
## Description

- 상품 관련 API 테스트 코드 작성

## Todo

- 상품 등록 테스트
  - [x] 성공 테스트
  - [x] 실패 테스트: 유효하지 않은 가격
  - [x] 실패 테스트: 유효하지 않은 카테고리
  - [x] 실패 테스트: 유효하지 않은 마감시간
- 상품 상세 조회 테스트
  - [x] 성공 테스트
  - [x] 실패 테스트: 유효하지 않은 상품Id 
  - [x] 실패 테스트: 삭제된 상품
- 상품 삭제 테스트
  - [x] 성공 테스트: 일반 유저(상품 소유자) 삭제 진행
  - [x] 성공 테스트: 관리자 삭제 진행
  - [x] 실패 테스트: 유효하지 않은 상품Id 
  - [x] 실패 테스트: 권한이 없는 유저
  - [x] 실패 테스트: 입찰 내역에 있는 상품
- 상품 수정 테스트
  - [x] 성공 테스트: 일반 유저(상품 소유자) 수정 진행
  - [x] 성공 테스트: 관리자 수정 진행
  - [x] 실패 테스트: 유효하지 않은 상품Id 
  - [x] 실패 테스트: 권한이 없는 유저
  - [x] 실패 테스트: 입찰 내역에 있는 상품
  - [x] 실패 테스트: 유효하지 않은 가격
  - [x] 실패 테스트: 유효하지 않은 카테고리
  - [x] 실패 테스트: 유효하지 않은 마감시간
