### ISSUE TITLE
상품 찜 관련 API 테스트

### ISSUE THREAD

**Issue by JangWooJin1** [Palgona/Backend#49]
## Description

- 상품 찜 관련 API 테스트

## Todo

- 상품 찜 등록 테스트
  - [ ] 성공 테스트
  - [ ] 실패 테스트: 유효하지 않은 상품id
  - [ ] 실패 테스트: 이미 추가된 찜 상품
- 상품 찜 삭제 테스트
  - [ ] 성공 테스트 
  - [ ] 실패 테스트: 유효하지 않은 상품id
  - [ ] 실패 테스트: 추가되지 않은 찜 상품
