### ISSUE TITLE
상품 CRUD API 오류 수정

### ISSUE THREAD

**Issue by JangWooJin1** [Palgona/Backend#89]
## Description

- 상품 CRUD API에서 발생하는 오류들 수정

## Todo

- [x] 상품 추가, 수정: 사진 파일 받는 형식 수정
- [x] 상품 삭제: 삭제 처리가 안되는 오류 수정
- [x] 상품 조회: 조회 쿼리가 제대로 동작하지 않는 오류 수정
